name: Visit Website

on:
  schedule:
    - cron:  '40 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Visit pomodorino
      run: curl https://pomodorino.streamlit.app/
    - name: Visit clockino
      run: curl https://clockino.streamlit.app/
    - name: Visit policumbent
      run: curl https://polic-mbent.streamlit.app/
